name: Build and Publish Python Package
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r requirements.txt
    - name: Build package
      run: |
        python -m build
    - name: Publish to PyPI
      # Remove the condition or modify it to include workflow_dispatch
      # if: startsWith(github.ref, 'refs/tags') || github.event_name == 'workflow_dispatch'
      env:
        TWINE_USERNAME: __token__  # Corrected format with underscores
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*
